// src/constants/airports.js

/* ======================================================
   ✈️ INTERNATIONAL AIRPORTS IN INDIA (Complete List)
====================================================== */

export const INTERNATIONAL_AIRPORTS = [
  {
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
    code: "AMD",
  },
  {
    name: "Sri Guru Ram Dass Jee International Airport",
    city: "Amritsar",
    code: "ATQ",
  },
  { name: "Kempegowda International Airport", city: "Bangalore", code: "BLR" },
  {
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
    code: "BBI",
  },
  { name: "Calicut International Airport", city: "Calicut", code: "CCJ" },
  { name: "Chandigarh International Airport", city: "Chandigarh", code: "IXC" },
  { name: "Chennai International Airport", city: "Chennai", code: "MAA" },
  { name: "Coimbatore International Airport", city: "Coimbatore", code: "CJB" },
  { name: "Indira Gandhi International Airport", city: "Delhi", code: "DEL" },
  { name: "Dabolim Airport", city: "Goa", code: "GOI" },
  {
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
    code: "GAU",
  },
  {
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    code: "HYD",
  },
  { name: "Imphal International Airport", city: "Imphal", code: "IMF" },
  { name: "Devi Ahilya Bai Holkar Airport", city: "Indore", code: "IDR" },
  { name: "Jaipur International Airport", city: "Jaipur", code: "JAI" },
  { name: "Kannur International Airport", city: "Kannur", code: "CNN" },
  { name: "Cochin International Airport", city: "Kochi", code: "COK" },
  {
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
    code: "CCU",
  },
  {
    name: "Chaudhary Charan Singh International Airport",
    city: "Lucknow",
    code: "LKO",
  },
  { name: "Madurai Airport", city: "Madurai", code: "IXM" },
  { name: "Mangalore International Airport", city: "Mangalore", code: "IXE" },
  {
    name: "Chhatrapati Shivaji International Airport",
    city: "Mumbai",
    code: "BOM",
  },
  {
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
    code: "NAG",
  },
  {
    name: "Jay Prakash Narayan International Airport",
    city: "Patna",
    code: "PAT",
  },
  { name: "Pune Airport", city: "Pune", code: "PNQ" },
  { name: "Bagdogra International Airport", city: "Siliguri", code: "IXB" },
  {
    name: "Sheikh ul Aalam International Airport",
    city: "Srinagar",
    code: "SXR",
  },
  { name: "Surat International Airport", city: "Surat", code: "STV" },
  {
    name: "Thiruvananthapuram International Airport",
    city: "Thiruvananthapuram",
    code: "TRV",
  },
  {
    name: "Tiruchirappalli International Airport",
    city: "Tiruchirappalli",
    code: "TRZ",
  },
  {
    name: "Lal Bahadur Shastri International Airport",
    city: "Varanasi",
    code: "VNS",
  },
  {
    name: "Visakhapatnam International Airport",
    city: "Visakhapatnam",
    code: "VTZ",
  },
];

/* ======================================================
   🏠 DOMESTIC AIRPORTS IN INDIA (Complete List)
====================================================== */

export const DOMESTIC_AIRPORTS = [
  { name: "Agatti Airport", city: "Agatti", code: "AGX" },
  { name: "Agra Air Force Station", city: "Agra", code: "AGR" },
  { name: "Maharaja Bir Bikram Airport", city: "Agartala", code: "IXA" },
  { name: "Kishangarh Airport", city: "Ajmer", code: "KQH" },
  { name: "Akola Airport", city: "Akola", code: "AKD" },
  { name: "Lengpui Airport", city: "Aizawl", code: "AJL" },
  { name: "Allahabad Airport", city: "Allahabad", code: "IXD" },
  { name: "Ambikapur Airport", city: "Ambikapur", code: "-" },
  { name: "Kazi Nazrul Islam Airport", city: "Asansol", code: "RDP" },
  { name: "Aurangabad Airport", city: "Aurangabad", code: "IXU" },
  { name: "Balurghat Airport", city: "Balurghat", code: "RGH" },
  { name: "Bathinda Airport", city: "Bathinda", code: "BUP" },
  { name: "Behala Airport", city: "Behala", code: "—" },
  { name: "Begumpet Airport", city: "Hyderabad", code: "—" },
  { name: "Bellary Airport", city: "Bellary", code: "BEP" },
  { name: "Belgaum Airport", city: "Belgaum", code: "IXG" },
  { name: "Jakkur Airfield", city: "Bengaluru", code: "—" },
  { name: "Bhavnagar Airport", city: "Bhavnagar", code: "BHU" },
  { name: "Raja Bhoj Airport", city: "Bhopal", code: "BHO" },
  { name: "Bhuj Airport", city: "Bhuj", code: "BHJ" },
  { name: "Nal Airport", city: "Bikaner", code: "BKB" },
  { name: "Bilaspur Airport", city: "Bilaspur", code: "PAB" },
  { name: "Bokaro Airport", city: "Bokaro", code: "BKR" },
  { name: "Cooch Behar Airport", city: "Cooch Behar", code: "COH" },
  { name: "Jolly Grant Airport", city: "Dehradun", code: "DED" },
  { name: "Dibrugarh Airport", city: "Dibrugarh", code: "DIB" },
  { name: "Dimapur Airport", city: "Dimapur", code: "DMU" },
  { name: "Diu Airport", city: "Diu", code: "DIU" },
  { name: "Pakyong Airport", city: "Gangtok", code: "PYG" },
  { name: "Gaya Airport", city: "Gaya", code: "GAY" },
  { name: "Hindon Airport", city: "Ghaziabad", code: "HDX" },
  { name: "Gorakhpur Airport", city: "Gorakhpur", code: "GOP" },
  { name: "Gwalior Airport", city: "Gwalior", code: "GWL" },
  { name: "Hisar Airport", city: "Hisar", code: "HSS" },
  { name: "Hubli Airport", city: "Hubli", code: "HBX" },
  { name: "Nadirgul Airport", city: "Hyderabad", code: "—" },
  { name: "Jabalpur Airport", city: "Jabalpur", code: "JLR" },
  { name: "Adampur Airport", city: "Jalandhar", code: "AIP" },
  { name: "Jalgaon Airport", city: "Jalgaon", code: "JLG" },
  { name: "Jammu Airport", city: "Jammu", code: "IXJ" },
  { name: "Jamnagar Airport", city: "Jamnagar", code: "JGA" },
  { name: "Sonari Airport", city: "Jamshedpur", code: "IXW" },
  { name: "Jaisalmer Airport", city: "Jaisalmer", code: "JSA" },
  { name: "Jeypore Airport", city: "Jeypore", code: "PYB" },
  { name: "Veer Surendra Sai Airport", city: "Jharsuguda", code: "JSA" },
  { name: "Jodhpur Airport", city: "Jodhpur", code: "JDH" },
  { name: "Jorhat Airport", city: "Jorhat", code: "JRH" },
  { name: "Kadapa Airport", city: "Kadapa", code: "CDP" },
  { name: "Gulbarga Airport", city: "Kalaburagi", code: "GBI" },
  { name: "Kandla Airport", city: "Kandla", code: "IXY" },
  { name: "Kangra Airport", city: "Kangra", code: "DHM" },
  { name: "Kanpur Airport", city: "Kanpur", code: "KNU" },
  { name: "Karnal Airport", city: "Karnal", code: "—" },
  { name: "Khajuraho Airport", city: "Khajuraho", code: "HJR" },
  { name: "Kolhapur Airport", city: "Kolhapur", code: "KLH" },
  { name: "Kollam Airport", city: "Kollam", code: "—" },
  { name: "Kota Airport", city: "Kota", code: "KTU" },
  { name: "Kullu-Manali Airport", city: "Kullu", code: "KUU" },
  { name: "Sahnewal Airport", city: "Ludhiana", code: "LUH" },
  { name: "Juhu Aerodrome", city: "Mumbai", code: "__" },
  { name: "Mysore Airport", city: "Mysore", code: "MYQ" },
  { name: "Nanded Airport", city: "Nanded", code: "NDC" },
  { name: "Nashik Airport", city: "Nashik", code: "ISK" },
  { name: "Lilabari Airport", city: "North Lakhimpur", code: "IXI" },
  { name: "Panagarh Airport", city: "Panagarh", code: "—" },
  { name: "Pantnagar Airport", city: "Pantnagar", code: "PGH" },
  { name: "Pasighat Airport", city: "Pasighat", code: "IXT" },
  { name: "Pathankot Airport", city: "Pathankot", code: "IXP" },
  { name: "Patiala Airport", city: "Patiala", code: "—" },
  { name: "Naini Saini Airport", city: "Pithoragarh", code: "NNS" },
  { name: "Puducherry Airport", city: "Pondicherry", code: "PNY" },
  { name: "Porbandar Airport", city: "Porbandar", code: "PBD" },
  {
    name: "Veer Savarkar International Airport",
    city: "Port Blair",
    code: "IXZ",
  },
  { name: "Rajahmundry Airport", city: "Rajahmundry", code: "RJA" },
  { name: "Swami Vivekananda Airport", city: "Raipur", code: "RPR" },
  { name: "Rajkot Airport", city: "Rajkot", code: "RAJ" },
  { name: "Birsa Munda Airport", city: "Ranchi", code: "IXR" },
  { name: "Salem Airport", city: "Salem", code: "SXV" },
  { name: "Satna Airport", city: "Satna", code: "TNI" },
  { name: "Shillong Airport", city: "Shillong", code: "SHL" },
  { name: "Shimla Airport", city: "Shimla", code: "SLV" },
  { name: "Shirdi Airport", city: "Shirdi", code: "SAG" },
  { name: "Silchar Airport", city: "Silchar", code: "IXS" },
  { name: "Solapur Airport", city: "Solapur", code: "SSL" },
  { name: "Tezpur Airport", city: "Tezpur", code: "TEZ" },
  { name: "Thoothukudi Airport", city: "Thoothukudi", code: "TCR" },
  { name: "Tirupati Airport", city: "Tirupati", code: "TIR" },
  { name: "Maharana Pratap Airport", city: "Udaipur", code: "UDR" },
  { name: "Vadodara Airport", city: "Vadodara", code: "BDQ" },
  { name: "Vijayawada Airport", city: "Vijayawada", code: "VGA" },
  { name: "Yavatmal Airport", city: "Yavatmal", code: "YTL" },
];

/* ======================================================
   ✅ ALL AIRPORTS COMBINED LIST
====================================================== */

export const ALL_INDIAN_AIRPORTS = [
  ...INTERNATIONAL_AIRPORTS,
  ...DOMESTIC_AIRPORTS,
];
