export const EVENT_CATEGORIES = [
  "Summit",
  "Ministerial",
  "Working Group",
  "Senior Official",
  "Head of Agencies",
  "Sherpa Meeting",
  "Workshop",
  "Webinar",
  "Others",
];

// ✅ COUNTRIES WITH BUILT-IN PHONE CODES (Replace your existing countries array)
export const countries = [
  { value: "afghanistan", label: "Afghanistan", phoneCode: "+93" },
  { value: "albania", label: "Albania", phoneCode: "+355" },
  { value: "algeria", label: "Algeria", phoneCode: "+213" },
  { value: "andorra", label: "Andorra", phoneCode: "+376" },
  { value: "angola", label: "Angola", phoneCode: "+244" },
  {
    value: "antigua-and-barbuda",
    label: "Antigua and Barbuda",
    phoneCode: "+1-268",
  },
  { value: "argentina", label: "Argentina", phoneCode: "+54" },
  { value: "armenia", label: "Armenia", phoneCode: "+374" },
  { value: "australia", label: "Australia", phoneCode: "+61" },
  { value: "austria", label: "Austria", phoneCode: "+43" },
  { value: "azerbaijan", label: "Azerbaijan", phoneCode: "+994" },
  { value: "bahamas", label: "Bahamas", phoneCode: "+1-242" },
  { value: "bahrain", label: "Bahrain", phoneCode: "+973" },
  { value: "bangladesh", label: "Bangladesh", phoneCode: "+880" },
  { value: "barbados", label: "Barbados", phoneCode: "+1-246" },
  { value: "belarus", label: "Belarus", phoneCode: "+375" },
  { value: "belgium", label: "Belgium", phoneCode: "+32" },
  { value: "belize", label: "Belize", phoneCode: "+501" },
  { value: "benin", label: "Benin", phoneCode: "+229" },
  { value: "bhutan", label: "Bhutan", phoneCode: "+975" },
  { value: "bolivia", label: "Bolivia", phoneCode: "+591" },
  {
    value: "bosnia-and-herzegovina",
    label: "Bosnia and Herzegovina",
    phoneCode: "+387",
  },
  { value: "botswana", label: "Botswana", phoneCode: "+267" },
  { value: "brazil", label: "Brazil", phoneCode: "+55" },
  { value: "brunei", label: "Brunei", phoneCode: "+673" },
  { value: "bulgaria", label: "Bulgaria", phoneCode: "+359" },
  { value: "burkina-faso", label: "Burkina Faso", phoneCode: "+226" },
  { value: "burundi", label: "Burundi", phoneCode: "+257" },
  { value: "cabo-verde", label: "Cabo Verde", phoneCode: "+238" },
  { value: "cambodia", label: "Cambodia", phoneCode: "+855" },
  { value: "cameroon", label: "Cameroon", phoneCode: "+237" },
  { value: "canada", label: "Canada", phoneCode: "+1" },
  {
    value: "central-african-republic",
    label: "Central African Republic",
    phoneCode: "+236",
  },
  { value: "chad", label: "Chad", phoneCode: "+235" },
  { value: "chile", label: "Chile", phoneCode: "+56" },
  { value: "china", label: "China", phoneCode: "+86" },
  { value: "colombia", label: "Colombia", phoneCode: "+57" },
  { value: "comoros", label: "Comoros", phoneCode: "+269" },
  { value: "congo", label: "Congo", phoneCode: "+242" },
  { value: "costa-rica", label: "Costa Rica", phoneCode: "+506" },
  { value: "croatia", label: "Croatia", phoneCode: "+385" },
  { value: "cuba", label: "Cuba", phoneCode: "+53" },
  { value: "cyprus", label: "Cyprus", phoneCode: "+357" },
  { value: "czech-republic", label: "Czech Republic", phoneCode: "+420" },
  { value: "denmark", label: "Denmark", phoneCode: "+45" },
  { value: "djibouti", label: "Djibouti", phoneCode: "+253" },
  { value: "dominica", label: "Dominica", phoneCode: "+1-767" },
  {
    value: "dominican-republic",
    label: "Dominican Republic",
    phoneCode: "+1-809",
  },
  { value: "ecuador", label: "Ecuador", phoneCode: "+593" },
  { value: "egypt", label: "Egypt", phoneCode: "+20" },
  { value: "el-salvador", label: "El Salvador", phoneCode: "+503" },
  { value: "equatorial-guinea", label: "Equatorial Guinea", phoneCode: "+240" },
  { value: "eritrea", label: "Eritrea", phoneCode: "+291" },
  { value: "estonia", label: "Estonia", phoneCode: "+372" },
  { value: "eswatini", label: "Eswatini", phoneCode: "+268" },
  { value: "ethiopia", label: "Ethiopia", phoneCode: "+251" },
  { value: "fiji", label: "Fiji", phoneCode: "+679" },
  { value: "finland", label: "Finland", phoneCode: "+358" },
  { value: "france", label: "France", phoneCode: "+33" },
  { value: "gabon", label: "Gabon", phoneCode: "+241" },
  { value: "gambia", label: "Gambia", phoneCode: "+220" },
  { value: "georgia", label: "Georgia", phoneCode: "+995" },
  { value: "germany", label: "Germany", phoneCode: "+49" },
  { value: "ghana", label: "Ghana", phoneCode: "+233" },
  { value: "greece", label: "Greece", phoneCode: "+30" },
  { value: "grenada", label: "Grenada", phoneCode: "+1-473" },
  { value: "guatemala", label: "Guatemala", phoneCode: "+502" },
  { value: "guinea", label: "Guinea", phoneCode: "+224" },
  { value: "guinea-bissau", label: "Guinea-Bissau", phoneCode: "+245" },
  { value: "guyana", label: "Guyana", phoneCode: "+592" },
  { value: "haiti", label: "Haiti", phoneCode: "+509" },
  { value: "honduras", label: "Honduras", phoneCode: "+504" },
  { value: "hungary", label: "Hungary", phoneCode: "+36" },
  { value: "iceland", label: "Iceland", phoneCode: "+354" },
  { value: "india", label: "India", phoneCode: "+91" },
  { value: "indonesia", label: "Indonesia", phoneCode: "+62" },
  { value: "iran", label: "Iran", phoneCode: "+98" },
  { value: "iraq", label: "Iraq", phoneCode: "+964" },
  { value: "ireland", label: "Ireland", phoneCode: "+353" },
  { value: "israel", label: "Israel", phoneCode: "+972" },
  { value: "italy", label: "Italy", phoneCode: "+39" },
  { value: "jamaica", label: "Jamaica", phoneCode: "+1-876" },
  { value: "japan", label: "Japan", phoneCode: "+81" },
  { value: "jordan", label: "Jordan", phoneCode: "+962" },
  { value: "kazakhstan", label: "Kazakhstan", phoneCode: "+7" },
  { value: "kenya", label: "Kenya", phoneCode: "+254" },
  { value: "kiribati", label: "Kiribati", phoneCode: "+686" },
  { value: "kuwait", label: "Kuwait", phoneCode: "+965" },
  { value: "kyrgyzstan", label: "Kyrgyzstan", phoneCode: "+996" },
  { value: "laos", label: "Laos", phoneCode: "+856" },
  { value: "latvia", label: "Latvia", phoneCode: "+371" },
  { value: "lebanon", label: "Lebanon", phoneCode: "+961" },
  { value: "lesotho", label: "Lesotho", phoneCode: "+266" },
  { value: "liberia", label: "Liberia", phoneCode: "+231" },
  { value: "libya", label: "Libya", phoneCode: "+218" },
  { value: "liechtenstein", label: "Liechtenstein", phoneCode: "+423" },
  { value: "lithuania", label: "Lithuania", phoneCode: "+370" },
  { value: "luxembourg", label: "Luxembourg", phoneCode: "+352" },
  { value: "madagascar", label: "Madagascar", phoneCode: "+261" },
  { value: "malawi", label: "Malawi", phoneCode: "+265" },
  { value: "malaysia", label: "Malaysia", phoneCode: "+60" },
  { value: "maldives", label: "Maldives", phoneCode: "+960" },
  { value: "mali", label: "Mali", phoneCode: "+223" },
  { value: "malta", label: "Malta", phoneCode: "+356" },
  { value: "marshall-islands", label: "Marshall Islands", phoneCode: "+692" },
  { value: "mauritania", label: "Mauritania", phoneCode: "+222" },
  { value: "mauritius", label: "Mauritius", phoneCode: "+230" },
  { value: "mexico", label: "Mexico", phoneCode: "+52" },
  { value: "micronesia", label: "Micronesia", phoneCode: "+691" },
  { value: "moldova", label: "Moldova", phoneCode: "+373" },
  { value: "monaco", label: "Monaco", phoneCode: "+377" },
  { value: "mongolia", label: "Mongolia", phoneCode: "+976" },
  { value: "montenegro", label: "Montenegro", phoneCode: "+382" },
  { value: "morocco", label: "Morocco", phoneCode: "+212" },
  { value: "mozambique", label: "Mozambique", phoneCode: "+258" },
  { value: "myanmar", label: "Myanmar", phoneCode: "+95" },
  { value: "namibia", label: "Namibia", phoneCode: "+264" },
  { value: "nauru", label: "Nauru", phoneCode: "+674" },
  { value: "nepal", label: "Nepal", phoneCode: "+977" },
  { value: "netherlands", label: "Netherlands", phoneCode: "+31" },
  { value: "new-zealand", label: "New Zealand", phoneCode: "+64" },
  { value: "nicaragua", label: "Nicaragua", phoneCode: "+505" },
  { value: "niger", label: "Niger", phoneCode: "+227" },
  { value: "nigeria", label: "Nigeria", phoneCode: "+234" },
  { value: "north-korea", label: "North Korea", phoneCode: "+850" },
  { value: "north-macedonia", label: "North Macedonia", phoneCode: "+389" },
  { value: "norway", label: "Norway", phoneCode: "+47" },
  { value: "oman", label: "Oman", phoneCode: "+968" },
  { value: "pakistan", label: "Pakistan", phoneCode: "+92" },
  { value: "palau", label: "Palau", phoneCode: "+680" },
  { value: "panama", label: "Panama", phoneCode: "+507" },
  { value: "papua-new-guinea", label: "Papua New Guinea", phoneCode: "+675" },
  { value: "paraguay", label: "Paraguay", phoneCode: "+595" },
  { value: "peru", label: "Peru", phoneCode: "+51" },
  { value: "philippines", label: "Philippines", phoneCode: "+63" },
  { value: "poland", label: "Poland", phoneCode: "+48" },
  { value: "portugal", label: "Portugal", phoneCode: "+351" },
  { value: "qatar", label: "Qatar", phoneCode: "+974" },
  { value: "romania", label: "Romania", phoneCode: "+40" },
  { value: "russia", label: "Russia", phoneCode: "+7" },
  { value: "rwanda", label: "Rwanda", phoneCode: "+250" },
  {
    value: "saint-kitts-and-nevis",
    label: "Saint Kitts and Nevis",
    phoneCode: "+1-869",
  },
  { value: "saint-lucia", label: "Saint Lucia", phoneCode: "+1-758" },
  {
    value: "saint-vincent-and-the-grenadines",
    label: "Saint Vincent and the Grenadines",
    phoneCode: "+1-784",
  },
  { value: "samoa", label: "Samoa", phoneCode: "+685" },
  { value: "san-marino", label: "San Marino", phoneCode: "+378" },
  {
    value: "sao-tome-and-principe",
    label: "Sao Tome and Principe",
    phoneCode: "+239",
  },
  { value: "saudi-arabia", label: "Saudi Arabia", phoneCode: "+966" },
  { value: "senegal", label: "Senegal", phoneCode: "+221" },
  { value: "serbia", label: "Serbia", phoneCode: "+381" },
  { value: "seychelles", label: "Seychelles", phoneCode: "+248" },
  { value: "sierra-leone", label: "Sierra Leone", phoneCode: "+232" },
  { value: "singapore", label: "Singapore", phoneCode: "+65" },
  { value: "slovakia", label: "Slovakia", phoneCode: "+421" },
  { value: "slovenia", label: "Slovenia", phoneCode: "+386" },
  { value: "solomon-islands", label: "Solomon Islands", phoneCode: "+677" },
  { value: "somalia", label: "Somalia", phoneCode: "+252" },
  { value: "south-africa", label: "South Africa", phoneCode: "+27" },
  { value: "south-korea", label: "South Korea", phoneCode: "+82" },
  { value: "south-sudan", label: "South Sudan", phoneCode: "+211" },
  { value: "spain", label: "Spain", phoneCode: "+34" },
  { value: "sri-lanka", label: "Sri Lanka", phoneCode: "+94" },
  { value: "sudan", label: "Sudan", phoneCode: "+249" },
  { value: "suriname", label: "Suriname", phoneCode: "+597" },
  { value: "sweden", label: "Sweden", phoneCode: "+46" },
  { value: "switzerland", label: "Switzerland", phoneCode: "+41" },
  { value: "syria", label: "Syria", phoneCode: "+963" },
  { value: "taiwan", label: "Taiwan", phoneCode: "+886" },
  { value: "tajikistan", label: "Tajikistan", phoneCode: "+992" },
  { value: "tanzania", label: "Tanzania", phoneCode: "+255" },
  { value: "thailand", label: "Thailand", phoneCode: "+66" },
  { value: "timor-leste", label: "Timor-Leste", phoneCode: "+670" },
  { value: "togo", label: "Togo", phoneCode: "+228" },
  { value: "tonga", label: "Tonga", phoneCode: "+676" },
  {
    value: "trinidad-and-tobago",
    label: "Trinidad and Tobago",
    phoneCode: "+1-868",
  },
  { value: "tunisia", label: "Tunisia", phoneCode: "+216" },
  { value: "turkey", label: "Turkey", phoneCode: "+90" },
  { value: "turkmenistan", label: "Turkmenistan", phoneCode: "+993" },
  { value: "tuvalu", label: "Tuvalu", phoneCode: "+688" },
  { value: "uganda", label: "Uganda", phoneCode: "+256" },
  { value: "ukraine", label: "Ukraine", phoneCode: "+380" },
  {
    value: "united-arab-emirates",
    label: "United Arab Emirates",
    phoneCode: "+971",
  },
  { value: "united-kingdom", label: "United Kingdom", phoneCode: "+44" },
  {
    value: "united-states-of-america",
    label: "United States of America",
    phoneCode: "+1",
  },
  { value: "uruguay", label: "Uruguay", phoneCode: "+598" },
  { value: "uzbekistan", label: "Uzbekistan", phoneCode: "+998" },
  { value: "vanuatu", label: "Vanuatu", phoneCode: "+678" },
  { value: "vatican-city", label: "Vatican City", phoneCode: "+39" },
  { value: "venezuela", label: "Venezuela", phoneCode: "+58" },
  { value: "vietnam", label: "Vietnam", phoneCode: "+84" },
  { value: "yemen", label: "Yemen", phoneCode: "+967" },
  { value: "zambia", label: "Zambia", phoneCode: "+260" },
  { value: "zimbabwe", label: "Zimbabwe", phoneCode: "+263" },
];

export const MINISTRIES = [
  {
    key: "Ministry_of_Prime_Ministers_Office",
    value: "Prime Minister's Office",
  },
  {
    key: "Ministry_of_Agriculture_and_Farmers_Welfare",
    value: "Ministry of Agriculture and Farmers Welfare",
  },
  { key: "Ministry_of_Ayush", value: "Ministry of Ayush" },
  {
    key: "Ministry_of_Chemicals_and_Fertilizers",
    value: "Ministry of Chemicals and Fertilizers",
  },
  { key: "Ministry_of_Civil_Aviation", value: "Ministry of Civil Aviation" },
  { key: "Ministry_of_Coal", value: "Ministry of Coal" },
  {
    key: "Ministry_of_Commerce_and_Industry",
    value: "Ministry of Commerce and Industry",
  },
  { key: "Ministry_of_Communications", value: "Ministry of Communications" },
  {
    key: "Ministry_of_Consumer_Affairs_Food_and_Public_Distribution",
    value: "Ministry of Consumer Affairs Food and Public Distribution",
  },
  {
    key: "Ministry_of_Corporate_Affairs",
    value: "Ministry of Corporate Affairs",
  },
  { key: "Ministry_of_Culture", value: "Ministry of Culture" },
  { key: "Ministry_of_Defence", value: "Ministry of Defence" },
  {
    key: "Ministry_of_Development_of_North_Eastern_Region",
    value: "Ministry of Development of North Eastern Region",
  },
  { key: "Ministry_of_Earth_Sciences", value: "Ministry of Earth Sciences" },
  { key: "Ministry_of_Education", value: "Ministry of Education" },
  {
    key: "Ministry_of_Electronics_and_Information_Technology",
    value: "Ministry of Electronics and Information Technology",
  },
  {
    key: "Ministry_of_Environment_Forest_and_Climate_Change",
    value: "Ministry of Environment Forest and Climate Change",
  },
  {
    key: "Ministry_of_External_Affairs",
    value: "Ministry of External Affairs",
  },
  { key: "Ministry_of_Finance", value: "Ministry of Finance" },
  {
    key: "Ministry_of_Fisheries_Animal_Husbandry_and_Dairying",
    value: "Ministry of Fisheries Animal Husbandry and Dairying",
  },
  {
    key: "Ministry_of_Food_Processing_Industries",
    value: "Ministry of Food Processing Industries",
  },
  {
    key: "Ministry_of_Health_and_Family_Welfare",
    value: "Ministry of Health and Family Welfare",
  },
  {
    key: "Ministry_of_Heavy_Industries",
    value: "Ministry of Heavy Industries",
  },
  { key: "Ministry_of_Home_Affairs", value: "Ministry of Home Affairs" },
  {
    key: "Ministry_of_Housing_and_Urban_Affairs",
    value: "Ministry of Housing and Urban Affairs",
  },
  {
    key: "Ministry_of_Information_and_Broadcasting",
    value: "Ministry of Information and Broadcasting",
  },
  { key: "Ministry_of_Jal_Shakti", value: "Ministry of Jal Shakti" },
  {
    key: "Ministry_of_Labour_and_Employment",
    value: "Ministry of Labour and Employment",
  },
  { key: "Ministry_of_Law_and_Justice", value: "Ministry of Law and Justice" },
  {
    key: "Ministry_of_Micro_Small_and_Medium_Enterprises",
    value: "Ministry of Micro Small and Medium Enterprises",
  },
  { key: "Ministry_of_Mines", value: "Ministry of Mines" },
  {
    key: "Ministry_of_Minority_Affairs",
    value: "Ministry of Minority Affairs",
  },
  {
    key: "Ministry_of_New_and_Renewable_Energy",
    value: "Ministry of New and Renewable Energy",
  },
  { key: "Ministry_of_Panchayati_Raj", value: "Ministry of Panchayati Raj" },
  {
    key: "Ministry_of_Parliamentary_Affairs",
    value: "Ministry of Parliamentary Affairs",
  },
  {
    key: "Ministry_of_Personnel_Public_Grievances_and_Pensions",
    value: "Ministry of Personnel Public Grievances and Pensions",
  },
  {
    key: "Ministry_of_Petroleum_and_Natural_Gas",
    value: "Ministry of Petroleum and Natural Gas",
  },
  { key: "Ministry_of_Power", value: "Ministry of Power" },
  { key: "Ministry_of_Railways", value: "Ministry of Railways" },
  {
    key: "Ministry_of_Road_Transport_and_Highways",
    value: "Ministry of Road Transport and Highways",
  },
  {
    key: "Ministry_of_Rural_Development",
    value: "Ministry of Rural Development",
  },
  {
    key: "Ministry_of_Science_and_Technology",
    value: "Ministry of Science and Technology",
  },
  { key: "Ministry_of_Shipping", value: "Ministry of Shipping" },
  {
    key: "Ministry_of_Skill_Development_and_Entrepreneurship",
    value: "Ministry of Skill Development and Entrepreneurship",
  },
  {
    key: "Ministry_of_Social_Justice_and_Empowerment",
    value: "Ministry of Social Justice and Empowerment",
  },
  {
    key: "Ministry_of_Statistics_and_Programme_Implementation",
    value: "Ministry of Statistics and Programme Implementation",
  },
  { key: "Ministry_of_Steel", value: "Ministry of Steel" },
  { key: "Ministry_of_Textiles", value: "Ministry of Textiles" },
  { key: "Ministry_of_Tourism", value: "Ministry of Tourism" },
  { key: "Ministry_of_Tribal_Affairs", value: "Ministry of Tribal Affairs" },
  {
    key: "Ministry_of_Women_and_Child_Development",
    value: "Ministry of Women and Child Development",
  },
  {
    key: "Ministry_of_Youth_Affairs_and_Sports",
    value: "Ministry of Youth Affairs and Sports",
  },
];

export const ORGANISATIONS = [
  { key: "Banco_Central_do_Brasil", value: "Banco Central do Brasil" },
  { key: "Bank_of_Russia", value: "Bank of Russia" },
  { key: "Reserve_Bank_of_India", value: "Reserve Bank of India" },
  { key: "Peoples_Bank_of_China", value: "People's Bank of China" },
  { key: "South_African_Reserve_Bank", value: "South African Reserve Bank" },
  { key: "Central_Bank_of_Egypt", value: "Central Bank of Egypt" },
  { key: "National_Bank_of_Ethiopia", value: "National Bank of Ethiopia" },
  { key: "Bank_Indonesia", value: "Bank Indonesia" },
  { key: "Central_Bank_of_the_Islamic_Republic_of_Iran", value: "Central Bank of the Islamic Republic of Iran" },
  { key: "Central_Bank_of_the_United_Arab_Emirates", value: "Central Bank of the United Arab Emirates" },
  { key: "Saudi_Central_Bank", value: "Saudi Central Bank" },
  { key: "New_Development_Bank", value: "New Development Bank" },
];
